import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'

const userDetails = [
  { Name: "First Name", Value: "John" },
  { Name: "Last Name", Value: "P" },
  { Name: "Email", Value: "Test@gmail" },
];

function Child (props) {
  return <div>
    <div><label>{props.Name}</label></div>
    <div><input type="text" defaultValue={props.Value}/></div>
  </div>
}

export default function Home() {
  const [user, setUser] = useState(userDetails);
  function onSubmit (event) {
    event.preventDefault();
    console.log(event.target.value);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={onSubmit}>
        {user.map(i => <Child key={i.Name} {...i}/>)}
        <input type="submit" value="Submit"/>
        </form>
      </main>

    </div>
  )
}
